### ISSUE TITLE
Generic ICS stopped working

### ISSUE THREAD

**Issue by lookas1** [mampfes/hacs_waste_collection_schedule#367] opened 2022-09-12 14:30 UTC
Hi,
I've been using waste_collection_schedule for quite some time without any issues. I've been using generic ICS file exported from Google Calendar where I've set the whole waste schedule. A few weeks ago it started to show "unknown" under my garbage sensors, today I found out why. Looks like fetching ICS is failing with the below error:

Logger: waste_collection_schedule.scraper
Source: custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py:143
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 15:55:06 (1 occurrences)
Last logged: 15:55:06

fetch failed for source ICS: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py", line 141, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 181, in fetch return self.fetch_url(self._url, self._params) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 209, in fetch_url return self._convert(r.text) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 216, in _convert dates = self._ics.convert(data) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 38, in convert events: List[Any] = icalevents.events( File "/usr/local/lib/python3.10/site-packages/icalevents/icalevents.py", line 50, in events found_events += parse_events(content, start=start, end=end) File "/usr/local/lib/python3.10/site-packages/icalevents/icalparser.py", line 356, in parse_events for dt in rule.between(after, end, inc=True): File "/usr/local/lib/python3.10/site-packages/dateutil/rrule.py", line 283, in between for i in gen: File "/usr/local/lib/python3.10/site-packages/dateutil/rrule.py", line 1401, in _iter while exlist and exlist[0] < ritem: File "/usr/local/lib/python3.10/site-packages/dateutil/rrule.py", line 1338, in __lt__ return self.dt < other.dt TypeError: can't compare offset-naive and offset-aware datetimes

**Comment by mampfes** [comment] 2022-09-17 12:15
probably duplicate of #294

Please try to add `version: 1` to your ICS source configuration.

See also docu: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md

**Comment by lookas1** [comment] 2022-09-19 09:58
@mampfes thank you it worked.

**Closed** 2022-09-19 18:20 UTC
