### ISSUE TITLE
[Bug]: Aha Region Hannover something changed?

### ISSUE THREAD

**Issue by deju1977** [mampfes/hacs_waste_collection_schedule#2450] opened 2024-08-13 19:54 UTC
### I Have A Problem With:

A specific source

### What's Your Problem

recently i got an error and no dates from AHA Regeion Hannover. See Log. Maybe samething changed on Website?

### Logs

```Shell
Logger: waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:147
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 21:42:44 (1 Vorkommnisse)
Zuletzt protokolliert: 21:42:44

fetch failed for source Zweckverband Abfallwirtschaft Region Hannover: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/aha_region_de.py", line 103, in fetch raise Exception( Exception: Invalid response from server, check you configuration if it is correct.
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by frathh** [comment] 2024-08-14 09:57
Also not working here. getting the same error message when trying to set it up via UI. My error message in the log looks slightly different:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:147
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 10:43:00 (1 Vorkommnisse)
Zuletzt protokolliert: 10:43:00

fetch failed for source Zweckverband Abfallwirtschaft Region Hannover: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/aha_region_de.py", line 62, in fetch r.raise_for_status() File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://www.aha-region.de/abholtermine/abfuhrkalender?gemeinde=Hannover&von=A&bis=%5B

**Comment by 5ila5** [comment] 2024-08-14 13:18
Duplicate of #2367

**Closed by 5ila5** 2024-08-14 13:18 UTC
