### ISSUE TITLE
[Bug]: Recycle BE - HTTP Error 401 Client Error: Unauthorized for url

### ISSUE THREAD

**Issue by tgilis** [mampfes/hacs_waste_collection_schedule#1740] opened 2024-01-29 10:47 UTC
### I Have A Problem With:

A specific source

### What's Your Problem

I added this with a configuration for the Recycle App (Belgium) and get the following error 
_requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.fostplus.be/recycle-public/app/v1/access-token_

### Source (if relevant)

recycleapp_be

### Logs

```Shell
Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 10:46:21 (1 occurrences)
Last logged: 10:46:21

fetch failed for source Recycle!: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/recycleapp_be.py", line 54, in fetch r.raise_for_status() File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.fostplus.be/recycle-public/app/v1/access-token
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: recycleapp_be
      args:
        postcode: POST_CODE
        street: STREET
        house_number: HOUSE_NUMBER
        add_events: ADD_EVENTS
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment] 2024-01-29 16:33
Duplicate of #1716

**Closed by 5ila5** 2024-01-29 16:33 UTC
