### ISSUE TITLE
Error HTTP 418 when using CitiesAppCom

### ISSUE THREAD

**Issue by AlpenFlizzer** [mampfes/hacs_waste_collection_schedule#1272] opened 2023-09-20 19:42 UTC
Hi, I installed the module as described, but I get the following trace on HASS startup:

```
2023-09-20 21:33:04.527 ERROR (SyncWorker_1) [waste_collection_schedule.source_shell] fetch failed for source App CITIES:
Traceback (most recent call last):
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch
    entries = self._source.fetch()
              ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/citiesapps_com.py", line 53, in fetch
    cities_apps = CitiesApps()
                  ^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/CitiesAppsCom.py", line 780, in __init__
    r.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 418 Client Error: I'm a Teapot for url: https://api.citiesapps.com/auth/guest
```

At first I tried my own config:
 ```
waste_collection_schedule:
  sources:
    - name: citiesapps_com
      args:
          city: Poysdorf
          calendar: Poysdorf, Wilhelmsdorf
      customize:
          - type: Biomüll
            alias: bio
            icon: mdi:trash-can
          - type: Gelber Sack
            alias: gelb
            icon: mdi:trash-can
          - type: Restmüll
            alias: rest
            icon: mdi:trash-can
          - type: Papier
            alias: papier
            icon: mdi:trash-can
          - type: Wertstoffsammelzentrum
            alias: wsz
            icon: mdi:trash-can
  fetch_time: "23:00"
  day_switch_time: "23:00"
```
Since that didn't work, I just pasted in the example:

```
waste_collection_schedule:
    sources:
    - name: citiesapps_com
      args:
        city: Fürstenfeld
        calendar: Haushalt Altenmarkt
```

Both, resulting in the same error.

**Comment by 5ila5** [comment] 2023-09-21 12:43
Duplicate of #1261

**Closed by 5ila5** 2023-09-21 12:43 UTC
