### ISSUE TITLE
N Somerset - only getting one bin type returned and seems like fetch service isn't working?

### ISSUE THREAD

**Issue by BobC76** [mampfes/hacs_waste_collection_schedule#1376] opened 2023-11-03 11:54 UTC
Hi
Struggling to work out how to get multiple bin schedules from my provider, North Somerset, UK.

From https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/nsomerset_gov_uk.md :

> "If collection data is available for the address provided, it will return food, rubbish and recycling waste collection dates."

Example postcode/URN that on the council site has two entries for Rubbish and Recycling:
```
waste_collection_schedule:
    sources:
    - name: nsomerset_gov_uk
      args:
        postcode: BS481RT
        uprn: 24128581
```

returns 
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/32709143/e00308d4-cebe-45ac-bdb5-a3ddca149b7f)

But the council web page gives:
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/32709143/bb83fd07-e072-41a7-a7c8-6d2c023a2b69)

Am I doing something wrong in the configuration?

Further question: calling service "waste_collection_schedule: Fetch data from all sources." doesn't seem to update the last updated date/time for the calendar entity...

I tried to enable debug logging for the integration but seem to have nothing further in the logs.

Thanks very much

**Comment by 5ila5** [comment] 2023-11-03 13:05
# Showing only one entry

I cannot reproduce your issue the example does return two entries for me tests:

```bash
➜ ./custom_components/waste_collection_schedule/waste_collection_schedule/test/test_sources.py -s nsomerset_gov_uk -lit
Testing source nsomerset_gov_uk ...
  found 1 entries for Town Hall, Walliscote Grove Road, Weston super Mare
    2023-11-09 : Recycling [mdi:recycle]
  found 2 entries for St Pauls, Walliscote Road, Weston super Mare
    2023-11-14 : Rubbish [mdi:trash-can]
    2023-11-07 : Recycling [mdi:recycle]
  found 2 entries for Christ Church Nailsea
    2023-11-08 : Rubbish [mdi:trash-can]
    2023-11-08 : Recycling [mdi:recycle]
```

# the Last updated calendar parameter

I'm not sure if this si a bug or intended it's possible that this only updates on actual change (depends how the calendar type behaves)

# Sensors

The calendar entity only shows the next event (or multiple "," separated if multiple are collected at the same day)
you  should be able to few your whole calendar in the calendar tab of homeassistant ({IP/HOSTNAME}:8123/calendar) for additional automation you should use sensors descried [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#configuring-sensors)

**Comment by gavink2** [comment] 2023-11-16 10:52
I'm seeing identical behaviour for waverley_gov_uk. There should be four different collections but one, Garden Waste Collection Service is not showing up in the calendar and the sensor I created for it is in unknown state. However, it does show up via the test script and via a manual query of the website.

Test:
```
gavin@singer:~/hacs_waste_collection_schedule/custom_components/waste_collection_schedule/waste_collection_schedule/test$ ./test_sources.py -s waverley_gov_uk  -lit
Testing source waverley_gov_uk ...
  found 12 entries for Example
    2023-11-16 : Food Waste Collection Service [mdi:food-apple]
    2023-11-16 : Recycling Collection Service [mdi:recycle]
    2023-11-23 : Domestic Waste Collection Service [mdi:trash-can]
    2023-11-23 : Food Waste Collection Service [mdi:food-apple]
    2023-11-24 : Garden Waste Collection Service [mdi:leaf]
    2023-11-30 : Food Waste Collection Service [mdi:food-apple]
    2023-11-30 : Recycling Collection Service [mdi:recycle]
    2023-12-07 : Domestic Waste Collection Service [mdi:trash-can]
    2023-12-07 : Food Waste Collection Service [mdi:food-apple]
    2023-12-08 : Garden Waste Collection Service [mdi:leaf]
    2023-12-14 : Food Waste Collection Service [mdi:food-apple]
    2023-12-14 : Recycling Collection Service [mdi:recycle]
  found 12 entries for Example No Postcode Space
    2023-11-16 : Food Waste Collection Service [mdi:food-apple]
    2023-11-16 : Recycling Collection Service [mdi:recycle]
    2023-11-23 : Domestic Waste Collection Service [mdi:trash-can]
    2023-11-23 : Food Waste Collection Service [mdi:food-apple]
    2023-11-24 : Garden Waste Collection Service [mdi:leaf]
    2023-11-30 : Food Waste Collection Service [mdi:food-apple]
    2023-11-30 : Recycling Collection Service [mdi:recycle]
    2023-12-07 : Domestic Waste Collection Service [mdi:trash-can]
    2023-12-07 : Food Waste Collection Service [mdi:food-apple]
    2023-12-08 : Garden Waste Collection Service [mdi:leaf]
    2023-12-14 : Food Waste Collection Service [mdi:food-apple]
    2023-12-14 : Recycling Collection Service [mdi:recycle]
```

Website:
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/82040769/f2b9a9c5-4d1d-4b8d-a06a-bc8354a25508)

HA Calendar:
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/82040769/001261c1-1272-4ca2-a5a8-3c17aa80e921)

HA Sensors:
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/82040769/8e98f1a2-b801-484a-ad31-a1d7508fea3f)

**Comment by BobC76** [comment] 2023-11-16 13:41
Hmm, I'm now getting all 3 expected entries for next week, but for only 1 week:

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/32709143/835a8256-bc3f-4389-98dd-7aec8cc3ddab)
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/32709143/d334b897-3368-43aa-aa21-af5575fdfe11)

(Unfortunately N Somerset post the garden waste schedule on a separate PDF for some reason best known to themselves.)

I used these values in the TEST_CASES:
`"Nailsea Park": {"uprn": "24068102", "postcode": "BS481BA"},`

**Comment by gavink2** [comment] 2023-11-16 15:37
I figured my issue out - the expected POST data for Waverley had a typo in the server-side implementation, which must have been corrected recently (`address_name_numer` corrected to `address_name_number`), so the house name wasn't being passed and I was getting a neighbour's schedule instead and they don't have garden bins. Will create a bug report.

**Comment by 5ila5** [comment] 2023-11-17 15:55
@gavink2 Bug report: #1422

@BobC76  the current implementation of nsomester_gov_uk only parses the date of the `Next collection date` row. I changed this behaviour in #1425 to also parse `Following collection date` this "improvement" will be part of release 1.44.0 or now as master (git) version (HACS: 3-dot menu -> redownload -> change version to master)

As PDF parsing is highly impracticable it would be best to use the [static/User Specified](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md) source for garden waste collections.

I will close this as complete

**Closed by 5ila5** 2023-11-17 15:55 UTC
