### ISSUE TITLE
[Bug]: Error accessing aha-region

### ISSUE THREAD

**Issue by yppiks** [mampfes/hacs_waste_collection_schedule#2434] opened 2024-08-12 13:37 UTC
### I Have A Problem With:

A specific source

### What's Your Problem

There has probably been a change on the website from https://www.aha-region.de/abholtermine/abfuhrkalender. 

### Logs

```Shell
Logger: waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:147
Integration: Waste Collection Schedule ([Dokumentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
Erstmals aufgetreten: 15:24:39 (1 Vorkommnisse)
Zuletzt protokolliert: 15:24:39

fetch failed for source Zweckverband Abfallwirtschaft Region Hannover: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/aha_region_de.py", line 103, in fetch raise Exception( Exception: Invalid response from server, check you configuration if it is correct.
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by AndrewSteel** [comment] 2024-08-12 15:28
Same here.

aha_region.py line 100:
**soup.find_all** searches for an entry "**_ical_apple_**" that does not exist (or no longer exists) on the website and then
lines 102 ff. throw the exception "Invalid response from server, check you configuration if it is correct."

**Comment by eumel21** [comment] 2024-08-12 17:48
It's already fixed in the current master-branch

**Comment by 5ila5** [comment] 2024-08-13 11:44
Duplicate of #2367

**Closed by 5ila5** 2024-08-13 11:44 UTC
