### ISSUE TITLE
problem with CITIES

### ISSUE THREAD

**Issue by PBA188** [mampfes/hacs_waste_collection_schedule#1297] opened 2023-10-03 07:19 UTC
erorr on Home Assistant 2023.9.3
Supervisor 2023.09.2 
Operating System 10.5
Frontend 20230911.0 - latest 

Error message:

fetch failed for source App CITIES: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/citiesapps_com.py", line 53, in fetch cities_apps = CitiesApps() ^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/CitiesAppsCom.py", line 780, in __init__ r.raise_for_status() File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 418 Client Error: I'm a Teapot for url: https://api.citiesapps.com/auth/guest

**Comment by 5ila5** [comment] 2023-10-03 11:54
Duplicate of #1261

**Closed by 5ila5** 2023-10-03 11:54 UTC
