### ISSUE TITLE
[Bug]: app_abfallplus_de de.k4systems.abfallinfoapp no results

### ISSUE THREAD

**Issue by Fireblade900rr** [mampfes/hacs_waste_collection_schedule#2017] opened 2024-04-24 14:20 UTC
### I Have A Problem With:

A specific source

### What's Your Problem

a week ago Kreis Euskirchen / Weilerswist worked but now its gone completely. Its still working on iPhone with abfallinfoapp.

### Source (if relevant)

de.k4systems.abfallinfoapp

### Logs

```Shell
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (Dokumentation)
Erstmals aufgetreten: 22. April 2024 um 14:54:37 (3 Vorkommnisse)
Zuletzt protokolliert: 01:27:02

fetch failed for source Apps by Abfall+: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/app_abfallplus_de.py", line 140, in fetch for d in self._app.generate_calendar(): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 786, in generate_calendar self.select_kommune() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 502, in select_kommune raise Exception(f"Region {self._region_search} not found.") Exception: Region Weilerswist not found.
```

### Relevant Configuration

```YAML
waste_collection_schedule:
    sources:
    - name: app_abfallplus_de
      args:
        app_id: de.k4systems.abfallinfoapp
        city: Weilerswist
        strasse: Große Heide
        hnr: X #replaced hnr with X
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ReneNulschDE** [comment] 2024-04-24 15:18
Please take a look here: #1989 . Scroll to the end, the thread has a lot of messages...

**Comment by 5ila5** [comment] 2024-04-24 16:00
Duplicate of #1989 

Das Problem wurde in mehreren PR gefixt: #1993  #2001 #2006

In der master Version sollte aber theoretisch alles klappen. HACS scheint aber öfter mal Probleme beim Updaten/Version ändern machen (du köanntest probieren die Integration zu löschen und neu zu installieren dann nochmal auf master umzustellen) oder die Datei `custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py` manuell anzupassen. (HA neustarten nicht vergessen)

**Closed by 5ila5** 2024-04-24 16:01 UTC

**Comment by Fireblade900rr** [comment] 2024-04-24 16:19
Oh ja, das wars, ich Danke Dir vielmals, ich hab die AppAbfallplusDe.py manuell ausgetauscht, Die hatte zwar heutiges Datum aber war nicht aktuell ! Nach Neustart gehts nun wieder. Echt Klasse !

**Comment by neostreamer** [comment] 2024-04-24 20:25
THX for the fix.
I have the issue realise first at today.

my app_id: de.k4systems.awbrastatt

Update from 1.47 to master now it works again!
