### ISSUE TITLE
[Bug]: portenf_sa_gov_au reporting incorrect dates

### ISSUE THREAD

**Issue by illuzn** [mampfes/hacs_waste_collection_schedule#1577] opened 2023-12-27 11:53 UTC
### I Have A Problem With:

A specific source

### What's Your Problem

The portenf_sa_gov_au sensor has been reporting incorrectly since it updated itself on 24 December 2023 (I can see this from HA logs). It appears that when there is 1 week or less left in the month "main-month" switches to the coming month and "other-month" becomes the current month.

Because of this, the integration reports the current collection next month and the next collections as in the past (and hides them).

The fix in #1110 by @5ila5 partly addresses the problem but it was not foreseeable to him that EOM would be treated this way. @5ila5 also noted that this might be an issue in that closed issue.

### Source (if relevant)

portenf_sa_gov_au

### Logs

```Shell
Output of test_sources.py:

Testing source portenf_sa_gov_au ...
  found 8 entries for Broadview, Regency Road, 565
    2024-01-26 : general-waste bin [mdi:trash-can]
    2024-01-26 : recycling bin [mdi:recycle]
    2023-12-02 : general-waste bin [mdi:trash-can]
    2023-12-02 : organics bin [mdi:leaf]
    2023-12-09 : general-waste bin [mdi:trash-can]
    2023-12-09 : recycling bin [mdi:recycle]
    2023-12-16 : general-waste bin [mdi:trash-can]
    2023-12-16 : organics bin [mdi:leaf]
  found 8 entries for 48 Floriedale Rd
    2024-01-26 : general-waste bin [mdi:trash-can]
    2024-01-26 : recycling bin [mdi:recycle]
    2023-12-02 : general-waste bin [mdi:trash-can]
    2023-12-02 : organics bin [mdi:leaf]
    2023-12-09 : general-waste bin [mdi:trash-can]
    2023-12-09 : recycling bin [mdi:recycle]
    2023-12-16 : general-waste bin [mdi:trash-can]
    2023-12-16 : organics bin [mdi:leaf]
  found 8 entries for 24 Margaret Terrace
    2024-01-28 : general-waste bin [mdi:trash-can]
    2024-01-28 : organics bin [mdi:leaf]
    2023-12-04 : general-waste bin [mdi:trash-can]
    2023-12-04 : recycling bin [mdi:recycle]
    2023-12-11 : general-waste bin [mdi:trash-can]
    2023-12-11 : organics bin [mdi:leaf]
    2023-12-18 : general-waste bin [mdi:trash-can]
    2023-12-18 : recycling bin [mdi:recycle]
  found 8 entries for Addison Road 91 with unit
    2024-01-28 : general-waste bin [mdi:trash-can]
    2024-01-28 : organics bin [mdi:leaf]
    2023-12-04 : general-waste bin [mdi:trash-can]
    2023-12-04 : recycling bin [mdi:recycle]
    2023-12-11 : general-waste bin [mdi:trash-can]
    2023-12-11 : organics bin [mdi:leaf]
    2023-12-18 : general-waste bin [mdi:trash-can]
    2023-12-18 : recycling bin [mdi:recycle]
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment] 2023-12-28 14:51
Fix will be part of release 1.45.0 or is available now as master (git) version (HACS: 3-dot menu -> redownload -> change version to master)

**Closed by 5ila5** 2023-12-28 14:51 UTC

**Comment by illuzn** [comment] 2024-01-16 19:35
@5ila5 looks like the logic is broken somewhere:

2024-01-17 05:57:30.836 ERROR (SyncWorker_21) [waste_collection_schedule.source_shell] fetch failed for source Port Adelaide Enfield, South Australia:

Traceback (most recent call last):

File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch

entries = self._source.fetch()

^^^^^^^^^^^^^^^^^^^^

File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/portenf_sa_gov_au.py", line 198, in fetch

date = datetime.strptime(f"{year}-{month}-{day}", "%Y-%B-%d").date()

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/usr/local/lib/python3.11/_strptime.py", line 568, in _strptime_datetime

tt, fraction, gmtoff_fraction = _strptime(data_string, format)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/usr/local/lib/python3.11/_strptime.py", line 534, in _strptime

julian = datetime_date(year, month, day).toordinal() - \

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ValueError: day is out of range for month

I'll dive into the code and look for myself when I have some time.

**Comment by 5ila5** [comment] 2024-01-18 09:40
Added a fix in #1693 you might want to have a look as this is not that easy to test as they change their calendar stays the same for multiple days

**Comment by illuzn** [comment] 2024-01-28 11:43
Updated to master commit: ce28496 and I'm receiving this error.

```
2024-01-28 22:12:13.888 ERROR (SyncWorker_9) [waste_collection_schedule.source_shell] fetch failed for source Port Adelaide Enfield, South Australia:
Traceback (most recent call last):
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch
entries = self._source.fetch()
^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/portenf_sa_gov_au.py", line 169, in fetch
"other-month" in today_div.attrs["class"]
^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'attrs'
```

**Comment by 5ila5** [comment] 2024-01-28 15:12
@illuzn I do not encounter this error. Could you try the example (works for me):

```yaml
waste_collection_schedule:
    sources:
    - name: portenf_sa_gov_au
      args:
        suburb: Rosewater
        street: Addison Road
        house_number: 91
        unit_number: 2
```

If this does work, you could take a look on [their website](https://ecouncil.portenf.sa.gov.au/T1PRWebPROD/eProperty/P1/PAE_WasteCollectionDates/Public.aspx?f=PAE.P1.BIN.PUBLICVIW) if there is any different in displaying the current day and report back

**Comment by illuzn** [comment] 2024-01-28 15:14
I think it's because local time just ticked over to 29/1/2024 (which starts a new week).
Sorry should have caught it earlier so we could bugfix (only noticed it because the custom component was updated today which reminded me to check this thread).

**Comment by illuzn** [comment] 2024-02-04 11:49
@5ila5 Sorry to keep bugging you... but it broke again this time with this error:
```
fetch failed for source Port Adelaide Enfield, South Australia: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/portenf_sa_gov_au.py", line 169, in fetch "other-month" in today_div.attrs["class"] ^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'attrs'
```

**Comment by 5ila5** [comment] 2024-02-05 08:28
I cannot reproduce this behavior, testing the source manually. The error indicates that there is no today_div (div inside the calendar with class today). The only reason I can think of why there shouldn't be one is some difference around 0:00 o clock? When did this error occur? Try restart HA to force a refetch. You could try changing the fetch_time but this more of a workaround than a real solution.

**Comment by illuzn** [comment] 2024-02-06 04:36
So strange... it's an intermittent bug... now it's working for me again and I can't reproduce it. Leave it with me I think I've got my head around how it's supposed to work and I'll try to come up with a solution for you to code review.
