### ISSUE TITLE
[Bug]: fetch failed for source Recycle!

### ISSUE THREAD

**Issue by iemand-dev** [mampfes/hacs_waste_collection_schedule#1953] opened 2024-04-08 18:27 UTC
### I Have A Problem With:

A specific source

### What's Your Problem

For (I unfortunately don't know how long, only recently moved and started HA again) the the Waste collection integration doesn't work anymore for the source Recycle!.
Navigating towards the API URL (https://api.fostplus.be/recycle-public/app/v1/streets) actually gives a 404.

Thank you for your support ;) 

### Source (if relevant)

recycleapp_be

### Logs

```Shell
This error originated from a custom integration.

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
integration: waste_collection_schedule (documentation)
First occurred: April 7, 2024 at 19:45:49 (2 occurrences)
Last logged: 01:21:00

fetch failed for source Recycle!: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/recycleapp_be.py", line 64, in fetch r.raise_for_status() File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.fostplus.be/recycle-public/app/v1/streets?qxxxxxxx&zipcodes=3200-24001
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: recycleapp_be
      args:
        postcode: 3200
        street: xxxxxxx
        house_number: 1
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment] 2024-04-12 12:32
They changed the url path. Fixed by #1971

This will be part of release 1.48.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Closed by 5ila5** 2024-04-12 12:32 UTC

**Comment by iemand-dev** [comment] 2024-04-12 13:32
@5ila5 
Changed version to master, redownload and reboot but it still results in errors.
Now "HTTPError: 400 Client Error: Bad Request".

Could you please advise?

> This error originated from a custom integration.
> 
> Logger: waste_collection_schedule.source_shell
> Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
> integration: waste_collection_schedule (documentation)
> First occurred: 14:55:34 (1 occurrences)
> Last logged: 14:55:34
> 
> fetch failed for source Recycle!: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/recycleapp_be.py", line 64, in fetch r.raise_for_status() File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.fostplus.be/recyclecms/app/v1/streets?q=xxxxxxx&zipcodes=3200-24001

**Comment by 5ila5** [comment] 2024-04-12 13:57
@iemand-dev unfortunately I cannot reproduce your issue.

```json
    "Begoniastraat 1, 3200 Gelrode": {
        "postcode": 3200,
        "street": "Begoniastraat",
        "house_number": 1,
    },
    "Haterbeekstraat 1, 3200 Aarschot": {
        "postcode": 3200,
        "street": "Haterbeekstra",
        "house_number": 1,
    }
``` 
Are working both fine on my side. You could try reinstalling this integration, mybe something got messed up when upgrading.

**Comment by iemand-dev** [comment] 2024-04-13 05:48
Hi @5ila5 
Thank you for the support but I found the root cause.
He doesn't like my address, it contains dots in the streetname and I think it is chocking on it.
I used the address of a neighboring street (which has the same schedule but no dots) and it works fine.

I tested with another random address that contains a dot and it gives me the same issue.
> Logger: waste_collection_schedule.source_shell
> Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
> integration: waste_collection_schedule (documentation)
> First occurred: 07:43:23 (1 occurrences)
> Last logged: 07:43:23
> 
> fetch failed for source Recycle!: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/recycleapp_be.py", line 64, in fetch r.raise_for_status() File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.fostplus.be/recyclecms/app/v1/streets?q=Th.+De+Beckerstraat&zipcodes=3200-24001

```
waste_collection_schedule:
  sources:
    - name: recycleapp_be
      args:
        postcode: 3200
        street: Th. De Beckerstraat
        house_number: 1
```

So for me this is "somewhat solved" with my workaround but might still be interesting to look into this one.
Thanks!

**Comment by 5ila5** [comment] 2024-04-13 13:47
@iemand-dev The source uses the street search you can find on [the website ](https://www.recycleapp.be/) testing around the script seems to not send out a search request at all when the query contains a `.` and does not find the street when providing the `Th` but `De Beckerstraat` works.

Do you think it would be a good idea to just strip everything left of a dot?

**Comment by iemand-dev** [comment] 2024-04-13 17:28
@5ila5 
Tested around with a few where the dot has a few more chars before it.

Kard. Mercierstraat, which becomes Mercierstraat 3200
Kapitein A.Tobbackstraat which becomes Tobbackstraat 3000
Burg.F.Steenostraat which becomes Steenostraat 3035
And my street of course

They all seem to work. 
Street names with a dot in are typically because the street was named after someone. The part before the dot is either their title (Kard. = Kardinaal, Burg. = Burgemeester) or their first name (Armand Tobback).

I think it it could work (remove everything before the last dot).
