### ISSUE TITLE
[Bug]: service aha_region_de fails to parse ics

### ISSUE THREAD

**Issue by derolli1976** [mampfes/hacs_waste_collection_schedule#1931] opened 2024-04-03 05:48 UTC
### I Have A Problem With:

A specific source

### What's Your Problem

It looks like there is a problem with the ics files retrieved from the api.
No new dates are being added to the schedule

### Source (if relevant)

aha_region_de

### Logs

```Shell
This error originated from a custom integration.

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
integration: waste_collection_schedule (documentation)
First occurred: April 2, 2024 at 08:50:11 (2 occurrences)
Last logged: 01:07:27

fetch failed for source Zweckverband Abfallwirtschaft Region Hannover: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/aha_region_de.py", line 117, in fetch dates = self._ics.convert(r.text) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 48, in convert events: List[Any] = icalevents.events( ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/icalevents/icalevents.py", line 57, in events found_events += parse_events( ^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/icalevents/icalparser.py", line 286, in parse_events raise ValueError("Content is invalid!") ValueError: Content is invalid!
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: aha_region_de
      args:
        gemeinde: "Langenhagen"
        strasse: "Wohldamm / Kaltenweide"
        hnr: "9"
        zusatz: ""
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment] 2024-04-03 12:06
Duplicate of #1912

**Closed by 5ila5** 2024-04-03 12:06 UTC
