### ISSUE TITLE
Source Issue - East Riding Gov

### ISSUE THREAD

**Issue by psidirect** [mampfes/hacs_waste_collection_schedule#1126] opened 2023-07-30 12:56 UTC
This source has been working perfectly up until the last few days. 

Error log is

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 13:50:05 (1 occurrences)
Last logged: 13:50:05

fetch failed for source East Riding of Yorkshire Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/eastriding_gov_uk.py", line 37, in fetch api_key = re.findall(REGEX["API_KEY"], r1.text)[0] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^ IndexError: list index out of range

**Comment by 5ila5** [comment] 2023-07-30 15:18
Duplicate of #1115 already fixed by #1119 

Fix will be part of release 1.42.0 or is available now as master/git version (up to date clone of this repository)

**Closed by 5ila5** 2023-07-30 15:18 UTC
Labels: duplicate, source defect
