### ISSUE TITLE
[Bug]: Source not pulling data back in the correct date/time format

### ISSUE THREAD

**Issue by mattclair** [mampfes/hacs_waste_collection_schedule#2430] opened 2024-08-12 01:52 UTC
### I Have A Problem With:

A specific source

### What's Your Problem

Configuring Republic Services with valid address from https://www.republicservices.com/schedule yields the following error:

The source returned an invalid response: "time data '2024-01-01T00:00:00.000Z' does not match format '%Y-%m-%dT00:00:00.0000000Z'". Please check the provided arguments and try again.

Using the source address from the example parameters gives the same result.

### Source (if relevant)

Republic Services

### Logs

```Shell
The source returned an invalid response: "time data '2024-01-01T00:00:00.000Z' does not match format '%Y-%m-%dT00:00:00.0000000Z'". Please check the provided arguments and try again.
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: republicservices_com
      args:
        street_address: !secret street_address
        method: 1
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment] 2024-08-13 11:42
Duplicate of #2420

**Closed** 2024-08-13 11:42 UTC
