### ISSUE TITLE
[Bug]: sysav_se not working anymore

### ISSUE THREAD

**Issue by teha36** [mampfes/hacs_waste_collection_schedule#1615] opened 2024-01-02 08:16 UTC
### I Have A Problem With:

A specific source

### What's Your Problem

Sysav in south Sweden is not working since (I think) beginning of December 2023, this is probably due to that the vendor Sysav has changed the API endpoint from
"https://www.sysav.se/api/my-pages/PickupSchedule/findAddress"
to
"https://ca-weu-sysav-edp-api-prod.icypond-fdc05156.westeurope.azurecontainerapps.io/api/PickupSchedules/foraddress"
...however I don't have a confirmation that this is the official new API endpoint

### Source (if relevant)

sysav_se

### Logs

```Shell
This is currently giving a correct response for my address
"https://ca-weu-sysav-edp-api-prod.icypond-fdc05156.westeurope.azurecontainerapps.io/api/PickupSchedules/foraddress/Vallgatan%205,%20Lomma"
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment] 2024-01-05 00:21
Duplicate of #1536

**Closed by 5ila5** 2024-01-05 00:21 UTC
