### ISSUE TITLE
City of Pforzheim.

### ISSUE THREAD

**Issue by wowik2018** [mampfes/hacs_waste_collection_schedule#641] opened 2023-01-24 19:23 UTC
Please add the city of Pforzheim.

**Comment by mampfes** [comment] 2023-01-25 17:55
Athos based...

**Comment by DanielR92** [comment] 2023-02-08 09:43
Short question, what do you mean with athos based?
Its a IT-Service provider, you mean to grab the data is quite complicated? 

Becuase no API?

**Comment by mampfes** [comment] 2023-02-08 19:02
Sorry for leaving out that information. There is a kind of library which is used by multiple districts. They use an URL which contains the string "athos", therefore I call it athos based.
The problem is that there are multiple versions of this library out there which behave slightly different. So we can't handle them by a single source. But there are already some sources out there which deal with athos service providers. It could be that the only necessary change to one of them is to change the URL to the one that your service provider is using.

**Comment by mampfes** [comment] 2023-04-01 07:12
fixed by #826

**Closed by mampfes** 2023-04-01 07:12 UTC
Labels: source request
