### ISSUE TITLE
Source Error Bielefeld

### ISSUE THREAD

**Issue by LudeGipsy** [mampfes/hacs_waste_collection_schedule#1334] opened 2023-10-16 23:22 UTC
Hi,
I get the following error with the bielefeld_de source:

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 01:12:55 (1 occurrences)
Last logged: 01:12:55

fetch failed for source Bielefeld: Traceback (most recent call last): File "/config/lsiopy/lib/python3.11/site-packages/icalendar/parser.py", line 340, in parts validate_token(name) File "/config/lsiopy/lib/python3.11/site-packages/icalendar/parser.py", line 128, in validate_token raise ValueError(name) ValueError: <!DOCTYPE HTML><HTML lang="de-DE"> During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/bielefeld_de.py", line 121, in fetch dates = self._ics.convert(r.text) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 38, in convert events: List[Any] = icalevents.events( ^^^^^^^^^^^^^^^^^^ File "/config/lsiopy/lib/python3.11/site-packages/icalevents/icalevents.py", line 57, in events found_events += parse_events( ^^^^^^^^^^^^^ File "/config/lsiopy/lib/python3.11/site-packages/icalevents/icalparser.py", line 288, in parse_events calendar = Calendar.from_ical(content) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/lsiopy/lib/python3.11/site-packages/icalendar/cal.py", line 330, in from_ical name, params, vals = line.parts() ^^^^^^^^^^^^ File "/config/lsiopy/lib/python3.11/site-packages/icalendar/parser.py", line 352, in parts raise ValueError( ValueError: Content line could not be parsed into parts: '<!DOCTYPE HTML><HTML lang="de-DE"> ': <!DOCTYPE HTML><HTML lang="de-DE">

**Comment by 5ila5** [comment] 2023-10-17 11:55
Duplicate of #1265

**Closed by 5ila5** 2023-10-17 11:55 UTC
