### ISSUE TITLE
[BUG] Unable to restart HA after adding waste_collection_schedule: to configuration.yaml

### ISSUE THREAD

**Issue by mbrammer** [mampfes/hacs_waste_collection_schedule#254] opened 2022-06-14 15:54 UTC
After adding the `waste_collection_schedule:` to my `configuration.yaml`, I am not able to do a config check or a restart of HA.
The config check request (`/api/config/core/check_config`) stagnates in the pending state.
I also did a `hass --script check_config` via console, but this script finished successfully. Not sure if it does exactly the same as the API script.

I installed waste_collection_schedule from **master** via HACS.
My HA version is **2022.6.3**, running in a Docker container.

My config:
```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "https://www.landkreis-harburg.de/abfallkalender/icalendar/ical.html?id=900000123&gebietOwner=20100&strukturID=1100&year={%Y}"
      customize:
        - type: Gelber Sack
          alias: Gelber Sack
          icon: mdi:recycle
        - type: Hausmüll 14-täglich
          alias: Hausmüll
          icon: mdi:trash-can
        - type: Altpapier
          alias: Altpapier
          icon: mdi:newspaper
        - type: Grünabfall
          alias: Grünabfall
          icon: mdi:tree
        - type: Biotonne
          alias: Biotonne
          icon: mdi:bio
      calendar_title: Abfall
  fetch_time: "04:00"
  day_switch_time: "16:00"
```

**Comment by mbrammer** [comment] 2022-06-14 21:00
Don't think so, but it worked after uninstalling master and installing version 1.21.0.
So it seem like there might be something wrong with the master branch.

**Comment by mampfes** [comment] 2022-06-16 14:40
Master branch is identical to 1.21.0, isn't it?

**Comment by mbrammer** [comment] 2022-06-16 18:09
I would have assumed that, too.
But than I can't explain myself why master is not working for me 🤷‍♂️

**Comment by mampfes** [comment] 2022-06-18 13:37
Thats why I think it is a duplicate of #220. Did you check again if master is now working also?

**Comment by mbrammer** [comment] 2022-06-20 10:21
I just tried. Changing from 1.21.0 to master worked.

**Closed** 2022-06-23 06:37 UTC
