### ISSUE TITLE
[Bug]: fetch failed for source Buckinghamshire Waste Collection - Former Chiltern, South Bucks or Wycombe areas

### ISSUE THREAD

**Issue by andy-81** [mampfes/hacs_waste_collection_schedule#2431] opened 2024-08-12 09:18 UTC
### I Have A Problem With:

A specific source

### What's Your Problem

I am not getting any information being pulled back from the Bucks Waste Collection portal. Below is a copy of the error log within Home Assistant showing the error in full. 

It appears to be having issues pulling the information from the portal.

I have * out the last 4 digits of the uprn as not sure how sensitive it is. The information has been pulling successfully for a while however has now stopped in the last few weeks. I have also tried using the uprn in the UI tool for adding (I had added the integration before the UI option was available) and this does not succeed either and shows an error while trying to add through the UI. 

I have also double checked the uprn is correct using the details in github to find them, these have not changed and are still correct.

Any help to resolve this issue would be appreciated.

### Source (if relevant)

Buckinghamshire Waste Collection - Former Chiltern, South Bucks or Wycombe areas

### Logs

```Shell
This error originated from a custom integration.

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:147
integration: Waste Collection Schedule (documentation)
First occurred: 08:27:42 (1 occurrences)
Last logged: 08:27:42

fetch failed for source Buckinghamshire Waste Collection - Former Chiltern, South Bucks or Wycombe areas: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 174, in _new_conn conn = connection.create_connection( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 95, in create_connection raise err File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection sock.connect(sa) TimeoutError: [Errno 110] Operation timed out During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 715, in urlopen httplib_response = self._make_request( ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 404, in _make_request self._validate_conn(conn) File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1060, in _validate_conn conn.connect() File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 363, in connect self.sock = conn = self._new_conn() ^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 179, in _new_conn raise ConnectTimeoutError( urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f5d804cbd10>, 'Connection to chiltern.gov.uk timed out. (connect timeout=None)') During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send resp = conn.urlopen( ^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 801, in urlopen retries = retries.increment( ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 594, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chiltern.gov.uk', port=443): Max retries exceeded with url: /collection-dates (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5d804cbd10>, 'Connection to chiltern.gov.uk timed out. (connect timeout=None)')) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/chiltern_gov_uk.py", line 38, in fetch r = session.get("https://chiltern.gov.uk/collection-dates") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 602, in get return self.request("GET", url, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send r = adapter.send(request, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 688, in send raise ConnectTimeout(e, request=request) requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='chiltern.gov.uk', port=443): Max retries exceeded with url: /collection-dates (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5d804cbd10>, 'Connection to chiltern.gov.uk timed out. (connect timeout=None)'))
```

### Relevant Configuration

```YAML
waste_collection_schedule:
    sources:
    - name: chiltern_gov_uk
      args:
        uprn: 10008054****
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment] 2024-08-13 11:23
Duplicate of #2383

**Closed by 5ila5** 2024-08-13 11:23 UTC
