### ISSUE TITLE
[Bug]: Issue with min_renovasjon

### ISSUE THREAD

**Issue by atxbyea** [mampfes/hacs_waste_collection_schedule#1666] opened 2024-01-12 11:26 UTC
### I Have A Problem With:

A specific source

### What's Your Problem

Does not initialize, I can't get the original integration from danielhiversen to work either, so I have logged a issue in that repo too.

### Source (if relevant)

min_renovasjon

### Logs

```Shell
`2024-01-12 10:37:02.703 ERROR (SyncWorker_13) [waste_collection_schedule.source_shell] fetch failed for source Min Renovasjon:
Traceback (most recent call last):
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch
    entries = self._source.fetch()
              ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/minrenovasjon_no.py", line 73, in fetch
    for f in json.loads(r.content):
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
```

### Relevant Configuration

```YAML
`
#waste_collection_schedule:
#  sources:
#    - name: minrenovasjon_no
#      args:
#        street_name: "Street"
#        house_number: "4"
#        street_code: "Code"
#        county_id: "County"
`
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment] 2024-01-14 15:01
Duplicate of #1482

**Comment by atxbyea** [comment] 2024-01-14 20:41
Not sure if this is a duplicate, running the master branch does not solve the issue.

**Comment by 5ila5** [comment] 2024-01-15 13:46
{
        "street_name": "Rådhustorget",
        "house_number": 2,
        "street_code": 2469,
        "county_id": 3024,
    }
test case works for me

**Comment by atxbyea** [comment] 2024-01-16 12:12
Yes, apparently the test case works for me too, but the moment I fill in my own address it fails, strange....

**Comment by 5ila5** [comment] 2024-01-16 12:55
can you test some other random address and report parameters for an address where it fails as well?

**Comment by atxbyea** [comment] 2024-01-16 13:42
It would appear that anything in my area errors out, whereas my parents house (different part of the country) works fine.

Does not work
`
        street_name: "Furubakken"
        house_number: "6"
        street_code: "2350"
        county_id: "3228"

        street_name: "Geminivegen"
        house_number: "6"
        street_code: "2625"
        county_id: "3228"

        street_name: "Damlivegen"
        house_number: "4"
        street_code: "1975"
        county_id: "3228"

        street_name: "Slyngvegen"
        house_number: "22"
        street_code: "4840"
        county_id: "3228"
`

Works fine: 

`
        street_name: "Radarvegen"
        house_number: "1"
        street_code: "28550"
        county_id: "5501"
`

**Comment by uvNikita** [comment] 2024-05-12 19:18
@atxbyea did you find the solution to this issue? I have the same problem.

**Comment by 5ila5** [comment] 2024-05-14 15:05
For me all the address work just fine:

```
Testing source minrenovasjon_no ...
  found 10 entries for Rådhustorget 2 2469 3024
    2024-05-14 : Glass-/metallemb [mdi:trash-can]
    2024-06-11 : Glass-/metallemb [mdi:trash-can]
    2024-05-21 : Plastemballasje [mdi:trash-can]
    2024-06-04 : Plastemballasje [mdi:trash-can]
    2024-05-21 : Papp og papir [mdi:newspaper-variant-multiple]
    2024-06-04 : Papp og papir [mdi:newspaper-variant-multiple]
    2024-05-23 : Matavfall [mdi:trash-can]
    2024-06-06 : Matavfall [mdi:trash-can]
    2024-05-27 : Restavfall [mdi:trash-can]
    2024-06-10 : Restavfall [mdi:trash-can]
  found 8 entries for Geminivegen, 6, 2625, 3228
    2024-05-20 : Restavfall [mdi:trash-can]
    2024-06-03 : Restavfall [mdi:trash-can]
    2024-05-20 : Matavfall [mdi:trash-can]
    2024-06-03 : Matavfall [mdi:trash-can]
    2024-06-10 : Papir [mdi:trash-can]
    2024-07-08 : Papir [mdi:trash-can]
    2024-06-10 : Plast [mdi:trash-can]
    2024-07-08 : Plast [mdi:trash-can]
  found 8 entries for Damlivegen 4 1975 3228
    2024-05-20 : Restavfall [mdi:trash-can]
    2024-06-03 : Restavfall [mdi:trash-can]
    2024-05-20 : Matavfall [mdi:trash-can]
    2024-06-03 : Matavfall [mdi:trash-can]
    2024-05-28 : Papir [mdi:trash-can]
    2024-06-25 : Papir [mdi:trash-can]
    2024-05-28 : Plast [mdi:trash-can]
    2024-06-25 : Plast [mdi:trash-can]
  found 8 entries for Slyngvegen 22 4840 3228
    2024-05-20 : Restavfall [mdi:trash-can]
    2024-06-03 : Restavfall [mdi:trash-can]
    2024-05-20 : Matavfall [mdi:trash-can]
    2024-06-03 : Matavfall [mdi:trash-can]
    2024-05-28 : Papir [mdi:trash-can]
    2024-06-25 : Papir [mdi:trash-can]
    2024-05-28 : Plast [mdi:trash-can]
    2024-06-25 : Plast [mdi:trash-can]
  found 4 entries for Radarvegen 1 28550 5501
    2024-05-16 : Optisk sortert avfall [mdi:trash-can]
    2024-05-24 : Optisk sortert avfall [mdi:trash-can]
    2024-05-28 : Glass/Metallemballasje [mdi:trash-can]
    2024-07-30 : Glass/Metallemballasje [mdi:trash-can]
```

**Comment by uvNikita** [comment] 2024-05-14 18:47
You are right, I missed I was running the old version. It works correctly after upgrade :+1:

**Closed** 2024-05-15 05:49 UTC
