### ISSUE TITLE
[Bug]: Calendar change - new Real Luzern website

### ISSUE THREAD

**Issue by tomik671108** [mampfes/hacs_waste_collection_schedule#2617] opened 2024-09-05 05:58 UTC
### I Have A Problem With:

A specific source

### What's Your Problem

The Real Luzern website has changed, waste collection dates can no longer be obtained.

[https://real-luzern.ch/aktuelles/neue-website-von-real-ist-online/](url)

### Source (if relevant)

https://real-luzern.ch/

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by tomik671108** [comment] 2024-09-05 06:00
I kindly ask for an update.

**Comment by lucadesimoni** [comment] 2024-09-05 08:14
Same behaviour for me, the URL for fetching seems unchanged, but some web elements probably changed which prevent data retrieval

**Comment by 5ila5** [comment] 2024-09-05 14:22
Duplicate of #2595

**Closed by 5ila5** 2024-09-05 14:22 UTC
