### ISSUE TITLE
possible recurring ics events issue

### ISSUE THREAD

**Issue by a-nicholls** [mampfes/hacs_waste_collection_schedule#7] opened 2020-05-23 14:43 UTC
I have had to publish my own calendar entries as my provider doesn't publish ICS events themselves, now our collection days are shifted whenever there is a public holiday so I created recurring events and moved the exceptions in Outlook and it has shared the ICS file

Found some info on ics formats and recurring events that may help
https://icalevents.com/4437-correct-handling-of-uid-recurrence-id-sequence/

[calendar.ics.txt](https://github.com/mampfes/hacs_waste_collection_schedule/files/4671956/calendar.ics.txt)

**Comment by mampfes** [comment] 2020-05-25 07:26
@a-nicholls Sorry, but I didn't understand your actual problem. Recurring events are supported since some days using a library from pypi and I fixed an issue 16 days ago. Could you describe your problem?

**Comment by a-nicholls** [comment] 2020-05-25 08:01
Sure created recurring events, and edited recurring exception (like this week)
![image](https://user-images.githubusercontent.com/51675087/82790145-7fb8f480-9e63-11ea-8881-239db96868db.png)

this produces the following ICS file if I download manually
[calendar.ics (2).txt](https://github.com/mampfes/hacs_waste_collection_schedule/files/4675869/calendar.ics.2.txt)

with the following config

configuration.yaml;
```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: !secret waste_collection_schedule_url
        offset: 0
```
sensor config

```yaml
- platform: waste_collection_schedule
  name: Bin days
  details_format: upcoming
  value_template: '{{value.types|join(" + ")}} in {{value.daysTo}} days'
  date_template: '{{value.types|join(" + ")}} in {{value.daysTo}} days'
```

this shows up in home assistant glance card;

![image](https://user-images.githubusercontent.com/51675087/82790991-e559b080-9e64-11ea-9444-470c51897f1c.png)

Doesn't show any blue bin collections, and shows black bin next collection after this week is in 102 days...

**Comment by mampfes** [comment] 2020-05-25 09:44
Hi, the library used for the recurring event handling doesn't like the ics file:

`ValueError: RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware`

If I remove the "Z" from UNTIL attribute in the RRULE statement (2 times), I get the following results:

```
    2020-05-28: Refuse black bin
    2020-05-29: Refuse black bin
    2020-06-04: Blue Recycle bin
    2020-06-11: Refuse black bin
    2020-06-18: Blue Recycle bin
    2020-06-25: Refuse black bin
    2020-07-02: Blue Recycle bin
    2020-07-09: Refuse black bin
    2020-07-16: Blue Recycle bin
    2020-07-23: Refuse black bin
    2020-07-30: Blue Recycle bin
    2020-08-06: Refuse black bin
    2020-08-13: Blue Recycle bin
    2020-08-20: Refuse black bin
    2020-08-27: Blue Recycle bin
    2020-09-03: Refuse black bin
    2020-09-04: Refuse black bin
    2020-09-10: Blue Recycle bin
```
Is this correct?

**Comment by a-nicholls** [comment] 2020-05-25 10:38
Well it shows the Blue Recycle bin from your results, but if you compare it from the calendar view that the ics file is generated from above the Thursday 28th May was modified as an exception to the 29th May, so it got the entry as an additional one on Friday 29th May but didn't remove the 28th Occurrence, the same thing happens in 2020-09-03 and 2020-09-04 (when in the UK there is a late summer holiday at the beginning of the week on 2020-08-31)

This link https://icalevents.com/4437-correct-handling-of-uid-recurrence-id-sequence/ provided information about how exceptions are interpretted

**Comment by mampfes** [comment] 2020-05-25 11:00
Thanks for the link, but the problem is that I don't interpret the ics file myself but use 2 libraries instead:

https://pypi.org/project/recurring-ical-events/
https://pypi.org/project/icalendar/

If there is a problem with exceptions is has to be fixed there - or if there is a better library available I could use this instead. But so far I don't know a better one.

**Comment by a-nicholls** [comment] 2020-05-25 11:22
Ah - I see from the first link they require test files to be published etc. before they will look at it, I'm quite new to the github stuff :)

**Comment by mampfes** [comment] 2020-05-25 12:02
Please let me know if you get any feedback. Maybe there is a hidden configuration option which would fix the issue but I don't know so far.

**Comment by mampfes** [comment] 2020-06-14 17:39
Hi, did you manage to solve your issue? If yes, I would like to close this issue here.

**Comment by a-nicholls** [comment] 2020-06-14 18:41
No unfortunately not, I think it's down to the datetime module; raised it as https://github.com/niccokunzmann/python-recurring-ical-events/issues/28 - unless you can provide any additional help to it?

**Comment by a-nicholls** [comment] 2020-07-01 19:08
I think the recurring events with the changes are now fixed - not sure if the order of the dates returned by the function matter?

**Comment by mampfes** [comment] 2020-07-02 06:54
OK, thank, then I will close the issue. The order of the returned dates doesn't matter, they will be sorted anyhow.

**Closed by mampfes** 2020-07-02 06:54 UTC
