### ISSUE TITLE
[Bug]: Auckland Council seems to be broken

### ISSUE THREAD

**Issue by DataBitz** [mampfes/hacs_waste_collection_schedule#2002] opened 2024-04-21 08:53 UTC
### I Have A Problem With:

A specific source

### What's Your Problem

Auckland Council collection is not returning any results.
Doesn't seem to be any logs reporting problems, fails silently?

### Source (if relevant)

aucklandcouncil_govt_nz

### Logs

```Shell
No relevant logs, please advise how to collect
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: aucklandcouncil_govt_nz
      args:
        area_number: 12342306525
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ReneNulschDE** [comment] 2024-04-21 15:03
Could you double check this? Here are the test results. The 8 Dickson Road has the same area_number like in your config.

```
(venv) rene@DERNHOME01 test ±|master|→ python3 test_sources.py -s aucklandcouncil_govt_nz
Testing source aucklandcouncil_govt_nz ...
  found 2 entries for 429 Sea View Road
  found 2 entries for 8 Dickson Road
  found 3 entries for with Food Scraps
  found 3 entries for 3 Andrew Road

```

**Comment by DataBitz** [comment] 2024-04-22 00:45
Not sure how to run this to test. This maybe a problem with my system only I guess.
Is there a way to run debug and would it include log entries like that?

**Comment by 5ila5** [comment] 2024-04-22 15:58
Duplicate of #1962

**Closed by 5ila5** 2024-04-22 15:58 UTC
