### ISSUE TITLE
Only "Unknown" returned for source cities.app

### ISSUE THREAD

**Issue by airman84** [mampfes/hacs_waste_collection_schedule#1270] opened 2023-09-19 10:32 UTC
Hello,

since some days I am reveiving below error for source cities.app
Configuration was not changed and worked well before.

Any Ideas?
Thank you

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 18. September 2023 um 16:46:12 (2 occurrences)
Last logged: 01:29:52

fetch failed for source App CITIES: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/citiesapps_com.py", line 53, in fetch cities_apps = CitiesApps() ^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/CitiesAppsCom.py", line 780, in __init__ r.raise_for_status() File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 418 Client Error: I'm a Teapot for url: https://api.citiesapps.com/auth/guest

**Comment by 5ila5** [comment] 2023-09-19 16:25
duplicate of #1261

**Closed by 5ila5** 2023-09-19 16:25 UTC
