### ISSUE TITLE
Caching ics file

### ISSUE THREAD

**Issue by ximum** [mampfes/hacs_waste_collection_schedule#563] opened 2023-01-04 11:49 UTC
Hi there and thank you for the fine integration of waste calendars for HA. I managed to add the calendar for my city served by mein-abfallkalender.de with this integration easily. A demo version if interesting: https://demo.mein-abfallkalender.de/webcal

They give the possibility to get a personal schedule for a specific street and kind of waste - sadly they limit the number of downloads per day/hour/unknown. The download link also integrates a userID which you have to verify by email.
I'm right now at the beginning of my HA installation and due to need to modify the config files more often I often need restarts, every restart initiates a new download of the ics and soon kills my 'api' limit.

Now to my maybe primitive idea - maybe there is an easy option to cache the daily downloaded file in a way which survives a restart?

Thank you!

**Comment by mampfes** [comment] 2023-01-04 14:36
Sorry, there is no easy way to cache the data. During normal operation (without a lot of restarts), the service provider will be queried only once per day - which should be ok.
Do they block your user id forever or just for a few hours? What you could also do is to disable waste_collection_schedule until you have a more stable configuration.
Therefore I would like to close this issue as NOT TO BE FIXED.

**Comment by dt215git** [comment] 2023-01-04 16:06
I guess it depends on what you're having to do to download the file and what format the file is.

Once you've validated the user account, if it's a fixed url that gives you and ics file you might be able to use HA's [downloader](https://www.home-assistant.io/integrations/downloader/) to get the file. If that works, then you could trigger that download on a 1/week schedule (or whatever the limitation is). You could then point your waste collection schedule config to the location that file is being downloaded to.

A bit of a complicated way of doing things, but if the >1 api call per day under normal use is causing issues it might be an interesting exercise... :laughing:

**Comment by ximum** [comment] 2023-01-04 16:13
> you might be able to use HA's [downloader](https://www.home-assistant.io/integrations/downloader/) to get the file
Thanks for the easy way - i was already scripting with my synology a way around - this is much easier!

**Comment by bbr111** [comment] 2023-01-04 17:32
@mampfes maybe we can add an parameter to fetch data only x days
or skip the refresh of data for x days.

**Comment by mampfes** [comment] 2023-01-07 08:23
@bbr111 This would only help in steady state (no restarts due to config changes) and if the API limit is less than one per day. But I assume that one fetch per day is ok and the problem is rather caused by a lot of restarts.

**Comment by mampfes** [comment] 2023-04-20 20:26
Not to be fixed

**Closed by mampfes** 2023-04-20 20:26 UTC
Labels: enhancement
