### ISSUE TITLE
[Bug]: Now data de.cmcitymedia.hokwaste

### ISSUE THREAD

**Issue by Shooter182** [mampfes/hacs_waste_collection_schedule#2019] opened 2024-04-25 17:06 UTC
### I Have A Problem With:

The integration in general

### What's Your Problem

Since a few days there are no more dates when the garbage is picked up.
I will be happy to send you a LOG if you tell me which one it should be.

### Source (if relevant)

de.cmcitymedia.hokwaste

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ReneNulschDE** [comment] 2024-04-28 05:46
The Hohenlohe-Kreis is managed by AppAbfall+ and not by cmcitymedia since several months. Therefore, I assume that you use the AppAbfall+ Source. Please check this [issue](https://github.com/mampfes/hacs_waste_collection_schedule/issues/1989#issuecomment-2073087420)

Btw: It would be good to share the config next time. This will save a lot of time.

**Comment by 5ila5** [comment] 2024-05-04 12:39
I'll close this as 
Duplicate of #1989

**Closed by 5ila5** 2024-05-04 12:39 UTC
