### ISSUE TITLE
[Bug]: Kirklees UK error during data download

### ISSUE THREAD

**Issue by rog2054** [mampfes/hacs_waste_collection_schedule#1399] opened 2023-11-09 16:22 UTC
### I Have A Problem With:

A specific source

### What's Your Problem

Was working fine for me for several weeks/months, then stopped working a few weeks ago.
Sensor's now just show status as 'Unknown' rather than number of days.

Council is Kirklees UK. Example postcode BD19 3AN.

Happy to help with further testing and troubleshooting if you give me a bit of guidance. Familiar with Python.

### Source (if relevant)

kirklees_gov_uk

### Logs

```Shell
Log details from HA System Log:

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 16:11:57 (1 occurrences)
Last logged: 16:11:57

fetch failed for source Kirklees Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/kirklees_gov_uk.py", line 63, in fetch PARAMS['ctl00$ctl00$cphPageBody$cphContent$thisGeoSearch$butGeoSearch'] = r0_bs4.find("input", {"id": "butGeoSearch"})['value'] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^ TypeError: 'NoneType' object is not subscriptable
```

### Relevant Configuration

```YAML
HA configuration:

waste_collection_schedule:
    sources:
    - name: kirklees_gov_uk
      args:
        door_num: 17
        postcode: "BD19 3AN"
      customize:
        - type: Domestic
          alias: Grey Bin
          picture: http://192.168.2.121:8123/local/grey-bin.png
          icon: mdi:trash-can
        - type: Recycling
          alias: Green Bin
          picture: http://192.168.2.121:8123/local/recycling-bin.png
          icon: mdi:recycle
      calendar_title: Bin Collections
    day_switch_time: "13:00"
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by rog2054** [comment] 2023-11-09 16:34
I'm not familiar with BeautifulSoup (never used it), but i think this is the webpage line is it tripping up on ('view source' line 390).

`<input type="submit" name="ctl00$ctl00$cphPageBody$cphContent$thisGeoSearch$butGeoSearch" value="Search" onclick="javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ctl00$cphPageBody$cphContent$thisGeoSearch$butGeoSearch&quot;, &quot;&quot;, true, &quot;GeoSearchValidationGroup&quot;, &quot;&quot;, false, false))" id="butGeoSearch" class="medium button green" type="submit" />`

**Comment by 5ila5** [comment] 2023-11-10 18:17
I cannot reproduce this error. Do you still encounter this? maybe a temporal issue on their end

**Comment by rog2054** [comment] 2023-11-11 16:03
> I cannot reproduce this error. Do you still encounter this? maybe a temporal issue on their end

Today it is polling without giving any errors in the HA logs, so must have been a temporary issue at their side (oddly the council website worked fine when i tried it manually before making the issue report here). Happy for this to be closed, thanks for your time.

**Comment by 5ila5** [comment] 2023-11-11 17:13
I will close this as complete. I can reopen this if the error reoccurs.

**Closed by 5ila5** 2023-11-11 17:13 UTC
