### ISSUE TITLE
EVS(muellmax) won’t work anymore

### ISSUE THREAD

**Issue by neturmel** [mampfes/hacs_waste_collection_schedule#2480] opened 2024-08-17 10:48 UTC
### I Have A Problem With:

A specific source

### What's Your Problem

Since a few days I only get an error when setting up/initialising my EVS source: Die Quelle hat eine ungültige Antwort zurückgegeben: "Content line could not be parsed into parts: '<!DOCTYPE html>': <!DOCTYPE html>". Bitte überprüfe die Argumente und versuche es erneut.

But I’d rather think the problem is on the EVS/muellmax side.

### Source (if relevant)

EVS(muellmax_de)

### Logs

```Shell
2024-08-17 12:25:51.779 ERROR (SyncWorker_1) [waste_collection_schedule.source_shell] fetch failed for source Müllmax:
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/icalendar/parser.py", line 340, in parts
validate_token(name)
File "/usr/local/lib/python3.12/site-packages/icalendar/parser.py", line 128, in validate_token
raise ValueError(name)
ValueError: <!DOCTYPE html>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch
entries = self._source.fetch()
^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/muellmax_de.py", line 145, in fetch
dates = self._ics.convert(r.text)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 48, in convert
events: List[Any] = icalevents.events(
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/icalevents/icalevents.py", line 57, in events
found_events += parse_events(
^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/icalevents/icalparser.py", line 288, in parse_events
calendar = Calendar.from_ical(content)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/icalendar/cal.py", line 330, in from_ical
name, params, vals = line.parts()
^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/icalendar/parser.py", line 352, in parts
raise ValueError(
ValueError: Content line could not be parsed into parts: '<!DOCTYPE html>': <!DOCTYPE html>
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment] 2024-08-17 12:08
Duplicate of #2468

**Closed by 5ila5** 2024-08-17 12:08 UTC
