### ISSUE TITLE
[Bug]: Zweckverband Abfallwirtschaft Region Hannover fails to load

### ISSUE THREAD

**Issue by kwithus** [mampfes/hacs_waste_collection_schedule#2489] opened 2024-08-18 09:54 UTC
### I Have A Problem With:

A specific source

### What's Your Problem

The source stopped working, it worked before with same configuration (which is same as on the website)

Example config also does not work

![image](https://github.com/user-attachments/assets/89c22f69-a7ef-4ebb-b174-a21e3c00747b)

### Source (if relevant)

Zweckverband Abfallwirtschaft Region Hannover

### Relevant Configuration

```YAML
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by Xinic** [comment] 2024-08-18 10:14
I can verify that it is not a singlue user issue. Started to fail couple of days ago (around wednesday I would say) for me. I just updated HA Core to 2024.8.2 to no avail.

**Comment by 5ila5** [comment] 2024-08-18 11:49
duplicate of #2367

I will release a new version now it will be part of the 2.1.0 release

**Closed** 2024-08-18 11:56 UTC
