### ISSUE TITLE
Problems with aw_harburg_de

### ISSUE THREAD

**Issue by b-reich** [mampfes/hacs_waste_collection_schedule#425] opened 2022-11-08 21:33 UTC
Hi, 

first thanks for this great addon.

my config:
```
waste_collection_schedule:
  sources:
    - name: aw_harburg_de
      args:
          level_1: "Buchholz"
          level_2: "Sprötze"
```
results in the following error:

```
home-assistant    | 2022-11-08 22:28:49.816 ERROR (SyncWorker_6) [waste_collection_schedule.scraper] fetch failed for source AW Harburg:
home-assistant    | Traceback (most recent call last):
home-assistant    |   File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py", line 141, in fetch
home-assistant    |     entries = self._source.fetch()
home-assistant    |   File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/aw_harburg_de.py", line 108, in fetch
home-assistant    |     dates = self._ics.convert(r.text)
home-assistant    |   File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 38, in convert
home-assistant    |     events: List[Any] = icalevents.events(
home-assistant    |   File "/usr/local/lib/python3.10/site-packages/icalevents/icalevents.py", line 50, in events
home-assistant    |     found_events += parse_events(content, start=start, end=end)
home-assistant    |   File "/usr/local/lib/python3.10/site-packages/icalevents/icalparser.py", line 250, in parse_events
home-assistant    |     raise ValueError('Content is invalid!')
home-assistant    | ValueError: Content is invalid!
```

**Comment by greenishhhh** [comment] 2022-11-12 09:09
see #410

**Comment by mampfes** [comment] 2022-11-15 07:14
duplicate of #410

**Closed by mampfes** 2022-11-15 07:14 UTC
