### ISSUE TITLE
[Bug]: GWA Kreis Unna is not working with abfallnavi.de. But the documentation says it is supported

### ISSUE THREAD

**Issue by Spartacus68** [mampfes/hacs_waste_collection_schedule#1629] opened 2024-01-03 16:31 UTC
### I Have A Problem With:

A specific source

### What's Your Problem

There is no region for selecting a city within "Kreis Unna" . You cannot selct the region from the the python script abfallnavi_de.py

But the Homepage is existing for kreis Unna: https://[abfallnavi](https://abfallnavi.de/unna/).de/unna/

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by Spartacus68** [comment] 2024-01-04 06:04
yes I know, but exacly this is not working as I described above! There is no region for this in abfallnavi!

**Comment by maxirnilian** [comment] 2024-01-04 09:02
You need to wait for the next release or use the master branch, support was added after version 1.44.0

**Comment by Spartacus68** [comment] 2024-01-04 13:22
I have installed the master branch and ithe region is also not included:
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/121975453/926a0f3a-5b02-4dcd-92e8-1d3c7cd9dc98)

I have had a call with the responsible developer at regio IT (the provider) and they told me, that a lot of regions are missing within abfallnavi_de and he also asks me, who has delivered the information for those regions. The information on this [website ](https://abfallnavi.api.bund.dev/)is not complete.

**Comment by Spartacus68** [comment] 2024-01-04 16:12
Hi all,

I am not very experienced with programming, but if I check the [Website ](https://[abfallnavi](https://abfallnavi.de/unna/).de/unna/) I can see that the region should be "unna" if I inspect the code: Found this here:

```
M.HOST="https://abfallapp.regioit.de/"
M.API-URL: "/abfall-app-unna/rest"
M.HOST + M.API_URL
```
I checked this configuration, bt the state of the entity is off.
```
waste_collection_schedule:
  sources:
    - name: abfallnavi_de
      args:
        service: unna
        ort: Unna
        strasse: Akazienweg
```
I think, that regioit changed the format of the Service URL. For me it is not in sync with this format: 
`https://{region}-abfallapp.regioit.de/abfall-app-{region}/rest`

Can someone check this? 
BTW the example from the documentation with "Coesfeld" is working for me!!

**Comment by Bobbin007** [comment] 2024-01-04 19:44
@Spartacus68 I ran into the same issue and reported it. With the commit #1557 the URL bug has been fixed.

**Comment by Spartacus68** [comment] 2024-01-04 20:02
@Bobbin007,

thanks, I was sure I have selected the master branch for installation but it seams to be that 1.44.0 is installed! I have to check, how I can switch to the master branch!

**Comment by Bobbin007** [comment] 2024-01-04 21:08
Glad it's working for you now.

**Comment by 5ila5** [comment] 2024-01-05 00:13
Duplicate of #1554

**Closed by 5ila5** 2024-01-05 00:14 UTC
