### ISSUE TITLE
[Bug]: Detected blocking call to import_module inside the event loop by custom integration 'waste_collection_schedule'

### ISSUE THREAD

**Issue by andyblac** [mampfes/hacs_waste_collection_schedule#2044] opened 2024-05-02 10:54 UTC
### I Have A Problem With:

The integration in general

### What's Your Problem

error shown in HA 2024.5 logs

### Logs

```Shell
Logger: homeassistant.util.loop
Source: util/loop.py:99
First occurred: 11:17:50 (1 occurrences)
Last logged: 11:17:50

Detected blocking call to import_module inside the event loop by custom integration 'waste_collection_schedule' at custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py, line 188: source_module = importlib.import_module( (offender: /config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py, line 188: source_module = importlib.import_module(), please report it to the author of the 'waste_collection_schedule' custom integration
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment] 2024-05-02 11:00
Duplicate of #2023

**Closed** 2024-05-02 11:00 UTC
