### ISSUE TITLE
[Source Request]: Three Rivers District Council Bin Collection feature

### ISSUE THREAD

**Issue by rajp1503** [mampfes/hacs_waste_collection_schedule#1834] opened 2024-02-26 18:39 UTC
### Municipality / Region

Three Rivers District Council, Herts, UK

### Collection Calendar Webpage

https://my.threerivers.gov.uk 

### Example Address

https://my.threerivers.gov.uk/en/AchieveForms/?mode=fill&form_uri=sandbox-publish://AF-Process-52df96e3-992a-4b39-bba3-06cfaabcb42b/AF-Stage-01ee28aa-1584-442c-8d1f-119b6e27114a/definition.json&process=1&process_uri=sandbox-processes://AF-Process-52df96e3-992a-4b39-bba3-06cfaabcb42b&process_id=AF-Process-52df96e3-992a-4b39-bba3-06cfaabcb42b&noLoginPrompt=1&accept=yes&consentMessageIds[]=4

### Collection Data Format

As html on a webpage

### Additional Information

Is it possible to get the scanning of the Three Rivers District Council bin collection info? At present, we have to sign up for a email which is sent out by them the day prior to collection. It is also possible to look on their website at https://my.threerivers.gov.uk/ too.

**Comment by 5ila5** [comment] 2024-02-27 18:20
Duplicate of #1646

**Closed by 5ila5** 2024-02-27 18:20 UTC
Labels: source request
