### ISSUE TITLE
[Bug]: NoneType' object is not subscriptable - Buckinghamshire Waste Collection, UPRN 100080513727  

### ISSUE THREAD

**Issue by mjvracing** [mampfes/hacs_waste_collection_schedule#2518] opened 2024-08-21 05:22 UTC
### I Have A Problem With:

A specific source

### What's Your Problem

Hi guys, 

My waste collection has been in unknown state for a few days,. If I try and add my area with the UI integration I get the following:

The source returned an invalid response: "'NoneType' object is not subscriptable". Please check the provided arguments and try again.

The YAML config I'm currently using logs the same 'NoneType' object error

I'm on Home Assistant 2024.7.2

Cheers

Mike
![Screenshot_20240821-061952](https://github.com/user-attachments/assets/f162a6ad-008b-4341-a6dc-31c559906bd7)

### Source (if relevant)

chiltern_gov_uk

### Logs

```Shell
This error originated from a custom integration.

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:147
integration: Waste Collection Schedule (documentation)
First occurred: 20 August 2024 at 07:36:11 (2 occurrences)
Last logged: 01:05:37

fetch failed for source Buckinghamshire Waste Collection - Former Chiltern, South Bucks or Wycombe areas: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/chiltern_gov_uk.py", line 44, in fetch form_url = form["action"] ~~~~^^^^^^^^^^ TypeError: 'NoneType' object is not subscriptable
```

### Relevant Configuration

```YAML
Added as a screenshot above
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment] 2024-08-21 13:19
Duplicate of #2383

**Closed by 5ila5** 2024-08-21 13:19 UTC
