### ISSUE TITLE
Home Assistant hangs when waste_collection_schedule is integrated.

### ISSUE THREAD

**Issue by Z0mbiel0ne** [mampfes/hacs_waste_collection_schedule#220] opened 2022-04-28 11:29 UTC
When i integrate waste_collection_schedule with 
```yaml
waste_collection_schedule: !include custom_config/waste_collection_schedule.yaml
```
I can no longer check the Home Assistant configuration. The animation loads infinitely.
![animation loads infinitely](https://user-images.githubusercontent.com/16578286/165739157-4451d69e-55c4-4f60-a939-9ea3b90c3a51.jpg)

When i reboot my Home Assistant, Home Assistant no longer starts successfully
![photo5422366056690858598](https://user-images.githubusercontent.com/16578286/165739158-46d8a5ee-3630-46ef-b9e5-29a5e2ceca6e.jpg)

All my integrations then fail to load
![photo5422366056690858599](https://user-images.githubusercontent.com/16578286/165739161-659166d0-8921-430a-a173-6bf9bbd1fdf8.jpg)

Unfortunately, the log does not show any error messages

**Versions**
Supervisor: [2022.04.0](https://github.com/home-assistant/supervisor/releases/tag/2022.04.0)
HA-Core: [2022.4.6](https://github.com/home-assistant/core/releases/tag/2022.4.6)
hacs_waste_collection_schedule: [1.18.0](https://github.com/mampfes/hacs_waste_collection_schedule/releases/tag/1.18.0)

@exashox

**Comment by mampfes** [comment] 2022-04-30 09:42
Sorry - I'm not able to reproduce this issue. Are you really sure that this endless loop is really caused by waste_collection_schedule?

Could you share your `waste_collection_schedule.yaml`?

**Comment by jojoman3** [comment] 2022-04-30 14:22
Hi, I have the exact same issue. When I add the waste collection config into the config yaml as described the configuration check goes into an endless loop. For me the restart is then even not triggered. 
When I then drop the entries from the config again everything works normal again and config check gives result within a second.

**Comment by mampfes** [comment] 2022-05-01 08:19
Hm, the configuation check for `waste_collection_schedule` is really simple. I don't expect the problem here.
But something else came into my mind: When you add `waste_collection_schedule` the first time, HA has to install some extra python packages (`icalendar recurring_ical_events icalevents bs4`). This may take a while and could also fail (for reasons I don't know). So, could you check if the installation of this packages could be the cause for the endless loop?

**Comment by Z0mbiel0ne** [comment] 2022-05-01 16:47
@mampfes here is the content of the `waste_collection_schedule.yaml`:

``` yaml
sources:
  - name: muellmax_de
    args:
      service: Usb
      mm_frm_str_sel: MyStreet
      mm_frm_hnr_sel: MyPLZ;MyCity;MyNr;
    customize:
      - type: USB Abfuhr Grau - Restmüll
        alias: Restmüll
      - type: USB Abfuhr Blau - Altpapier
        alias: Altpapier
      - type: USB Abfuhr Gelb - kombinierte Wertstofftonne
        alias: Wertstoffe
      - type: USB Abfuhr Tannenbäume
        alias: Weihnachtsbäume
fetch_time: "01:00"
```

waste_collection_schedule worked months without a problem, so the python packages should be installed, but I will check if this causes the endless loop.

**Comment by jojoman3** [comment] 2022-05-03 09:46
Wie kann ich das python Paket checken? Ich habe zwar Terminal Zugriff via UI, aber welcher Befehl ist das dann? die mir bekannten python befehle existieren da nicht in der Umgebung

**Comment by Z0mbiel0ne** [comment] 2022-05-03 15:05
@jojoman3 you can check your installed python modules with the following commands:

```bash
sudo docker exec -it homeassistant /bin/bash
pip list
```
and check the output against https://github.com/mampfes/hacs_waste_collection_schedule/blob/3373bec55228f1408b4155418e83c7bade0b7670/custom_components/waste_collection_schedule/manifest.json#L5

**Comment by mampfes** [comment] 2022-05-03 16:53
Great progress, thanks!

I think this is a HA core issue, because custom components can be also installed manually (without HACS).

**Comment by mampfes** [comment] 2022-05-22 17:16
Can we close this issue?

**Closed** 2022-05-22 19:30 UTC
