### ISSUE TITLE
Parsing error. ValueError: time data '13 Augu 2023' does not match format '%d %B %Y' (Cherwell Council, UK)

### ISSUE THREAD

**Issue by pbulteel** [mampfes/hacs_waste_collection_schedule#1116] opened 2023-07-26 09:28 UTC
There seems to be an issue: 

`
2023-07-24 21:45:07.093 ERROR (SyncWorker_6) [waste_collection_schedule.source_shell] fetch failed for source Cherwell District Council:
Traceback (most recent call last):
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch
    entries = self._source.fetch()
              ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/cherwell_gov_uk.py", line 56, in fetch
    dt = datetime.strptime(dt, "%d %B %Y")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '13 Augu 2023' does not match format '%d %B %Y'
`
The HTML on the site seems ok - and I'm not seeing where the 13 of August is coming from. There are two bin collection dates showing. 

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/5732473/0b0209be-d52b-466c-8406-56ca22460f88)

Unfortunately, the HTML below gets parsed

`
<img class="icon bin-collection-tasks__icon" src="https://forms.cherwell.gov.uk/images/bin-collections/bin-collection-green.svg" alt="green bin collection">
<h3 class="bin-collection-tasks__heading"><span class="visually-hidden">Your next </span>Green Bin<span class="visually-hidden"> collection</span></h3>
<div class="bin-collection-tasks__content">
<p class="bin-collection-tasks__day">Tuesday</p>
<p class="bin-collection-tasks__date">8th August</p>
`
So, I'm including an image.

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/5732473/272bfd6a-ace5-4561-bd34-8cc95c129fbe)

Any ideas about what could be happening here?

-P

**Comment by cgms** [comment] 2023-07-26 18:39
found the root cause before checking here! thanks for confirming my analysis that the regex is the problem. Have you got a fix for the regex we can apply locally? (i am useless at regex)

**Comment by 5ila5** [comment] 2023-07-29 09:22
fixed by #1118
Fix will be part of release 1.42.0 or is available now as master/git version.

If there are still errors with the source let us know here.

**Closed by 5ila5** 2023-07-29 09:22 UTC
