### ISSUE TITLE
[Bug]: Republic Services, Invalid Response, Time Data

### ISSUE THREAD

**Issue by PapaMater** [mampfes/hacs_waste_collection_schedule#2425] opened 2024-08-10 23:17 UTC
### I Have A Problem With:

A specific source

### What's Your Problem

When trying to add a republic services source, the configuration fails due to an invalid response (see pasted logs). 

The invalid response happens regardless of attempting to configure via UI or by yaml. Same error.

In an attempt to sanity check, I copied the exact configuration (including address/location) from the example configuration. The result is the same.

### Source (if relevant)

Republic Services

### Logs

```Shell
The source returned an invalid response: "time data '2024-01-01T00:00:00.000Z' does not match format '%Y-%m-%dT00:00:00.0000000Z'". Please check the provided arguments and try again.
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: republicservices_com
      args:
        street_address: "8957 Park Meadows Dr, Elk Grove, CA 95624"
        method: 1
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment] 2024-08-11 11:23
Duplicate of #2420

**Closed by 5ila5** 2024-08-11 11:23 UTC
