### ISSUE TITLE
Detected I/O inside the event loop @ stadtreinigung.py

### ISSUE THREAD

**Issue by Liese2007** [mampfes/hacs_waste_collection_schedule#3] opened 2020-05-02 05:36 UTC
Hi,
seems the same warning like Issue #1 , but different .py file so I raised additional one.

Home Assistant: 109.1

Error log shows:
`2020-05-02 01:00:00 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for waste_collection_schedule doing I/O at custom_components/waste_collection_schedule/package/source/stadtreinigung_hamburg.py, line 36: data=args`

Gruss
Jörg

**Comment by mampfes** [comment] 2020-05-02 12:04
Duplicate of #1 
Fixed by commit e588003c.

**Closed** 2020-05-05 05:58 UTC
