### ISSUE TITLE
Buckinghamshire Waste Collection source changes

### ISSUE THREAD

**Issue by danoev** [mampfes/hacs_waste_collection_schedule#2551] opened 2024-08-24 21:41 UTC
Buckinghamshire Waste Collection - Former Chiltern, South Bucks or Wycombe areas

Source website has now changed and the fetch url "https://chiltern.gov.uk/collection-dates" no longer exists.

https://www.buckinghamshire.gov.uk/waste-and-recycling/find-out-when-its-your-bin-collection/ seems to be it's replacement.

**Comment by 5ila5** [comment] 2024-08-24 21:49
Duplicate of #2383


This is already resolved

> You can now use the iapp_itouchvision_com source. The chiltern_gov_uk source does work but will show a warning in your logs to move to the iapp_itouchvision_com source. GUI configuration should be moved to the iapp_itouchvision_com source automatically.
> 
> This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

from https://github.com/mampfes/hacs_waste_collection_schedule/issues/2383#issuecomment-2302235507

**Closed** 2024-08-24 21:49 UTC
