### ISSUE TITLE
[Bug]: recycleapp_be / fostplus.be api problems ?

### ISSUE THREAD

**Issue by bibikiwi** [mampfes/hacs_waste_collection_schedule#1753] opened 2024-02-01 13:43 UTC
### I Have A Problem With:

A specific source

### What's Your Problem

Since a few days, I don't get data anymore, the logs seem to indicate an API authentication issue

### Source (if relevant)

recycleapp_be

### Logs

```Shell
2024-02-01 14:26:22.551 ERROR (SyncWorker_8) [waste_collection_schedule.source_shell] fetch failed for source Recycle!:
Traceback (most recent call last):
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch
    entries = self._source.fetch()
              ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/recycleapp_be.py", line 54, in fetch
    r.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.fostplus.be/recycle-public/app/v1/access-token
```

### Relevant Configuration

```YAML
config used (address changed to the town hall for privacy, but should give same results) :


waste_collection_schedule:
  sources:
    - name: recycleapp_be
      args:
        postcode: 1730
        street: Gemeenteplein
        house_number: 1
        add_events: True
      customize:
        - type: PMD
          alias: PMD (plastique)
          icon: mdi:bottle-soda-classic-outline
        - type: Restafval
          alias:  Restafval (poubelle)
          icon: mdi:trash-can-outline
        - type: Paper-cardboard
          alias: Papier & Karton
          icon: mdi:package-variant

```
```


### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment] 2024-02-02 08:35
Duplicate of #1716

**Closed by 5ila5** 2024-02-02 08:35 UTC
